#!/bin/sh
### BEGIN INIT INFO
# Provides:          github-webhook-daemon
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Calls a shell command when a webhook notification is received
# Description: Calls a shell command when a webhook notification is received
### END INIT INFO

NAME=github-webhook-daemon
SELF=/etc/init.d/$NAME
CONF=/etc/$NAME.conf
BIN=/usr/local/bin/$NAME.py
LOG=/dev/null
PIDF=/var/run/$NAME.pid

do_start() {
	start-stop-daemon --start --exec $BIN $CONF >> $LOG --pidfile $PIDF \
		--background
}

do_stop() {
	start-stop-daemon --stop --pidfile $PIDF
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		do_stop
		do_start
		;;
	*)
		echo "Usage: $SELF {start|stop|restart}"
		exit 1
		;;
esac

exit 0
